dz 9 , первое в новом репозитории
Bakivh/admin-panel pull request #1
Opened 2022-02-26 12:11 UTC by Bakivh

2022-03-04 08:18 UTC, Muslik requested changes
Удалите head, body, html из разметки

2022-03-04 08:18 UTC, Muslik commented on src/App.js
> +    <html lang="en">
html, head, body не нужно вставлять в jsx

2022-03-08 17:13 UTC, Bakivh commented on src/App.js
> +    <html lang="en">
исправил, но обернул все в один тег, иначе ругается

2022-03-08 21:07 UTC, Muslik approved these changes
Заменить class на classNames

2022-03-08 21:07 UTC, Muslik commented on src/App.js
> +    <div class="app">
class замените на className

2022-03-08 21:20 UTC, Bakivh commented on src/App.js
> +    <div class="app">
заменил, а зачем это?

2022-03-08 21:20 UTC, merged