Сделал первый компонент Input
Bakivh/admin-panel pull request #2
Opened 2022-03-29 21:39 UTC by Bakivh

Джабраил посмотри пожалуйста все ли верно на примере одного компонента.
Если все ок то сделаю остальные по аналогии.
Спасибо.

2022-03-30 12:18 UTC, Muslik requested changes

2022-03-30 12:18 UTC, Muslik commented on src/common/components/Input/Input.js
> +    [styles.inputText_incorrect]: incorrect,
Зачем нужны отдельные классы. Выше они уже есть. Сделайте зависимость в css
```css
.input>incorrect .inputText
```

2022-03-30 12:18 UTC, Muslik commented on src/common/components/Input/Input.js
> +  children = "",
Это не children. Это именно label

2022-03-30 12:18 UTC, Muslik commented on src/common/components/Input/Input.js
> +          {incorrect && (
Кнопка крестика показывается когда поле заполнено, а не когда incorrect

2022-03-30 12:18 UTC, Muslik commented on src/common/components/Input/Input.js
> +        <div className={styles.label}>{children}</div>
Я бы все таки разделил input и label. (Я в телеграмме писал пример на основе чекбокса)
https://ibb.co/8dbwS0z - у вас будет пример где для второго инпута label не нужен. Как вы будете выкручиваться?

2022-03-30 12:18 UTC, Muslik commented on src/common/components/Input/Input.js
> +          {disabled && <img className={styles.buttonIcon} src={lockedIcon} />}
Это не buttonIcon. Это просто icon

2022-03-30 12:18 UTC, Muslik commented on src/common/components/Input/Input.js
> +            type="text"
А если захочу другой тип?

2022-03-30 12:18 UTC, Muslik commented on src/common/components/Input/Input.js
> +            defaultValue={value}
defaultValue и value это разные понятия. props должен называться именно defaultValue

2022-03-30 12:18 UTC, Muslik commented on src/common/components/Input/Input.js
> +import xMediumIcon from "../../icons/x-medium.svg";
Я в телеграм показывал пример с абсолютными импортами. Это отличный вариант использовать их.

2022-03-30 12:18 UTC, Muslik commented on src/common/components/Input/Input.js
> +import cx from "classnames";
js -> jsx

2022-03-30 18:31 UTC, Bakivh commented on src/common/components/Input/Input.js
> +    [styles.inputText_incorrect]: incorrect,
изменил

2022-03-30 18:34 UTC, Bakivh commented on src/common/components/Input/Input.js
> +  children = "",
ок, поменял

2022-03-30 18:45 UTC, Bakivh commented on src/common/components/Input/Input.js
> +          {incorrect && (
а это как надо делать , получается через обработчик onChange ? Менять класс и хайдить иконку?

2022-03-30 19:00 UTC, Bakivh commented on src/common/components/Input/Input.js
> +        <div className={styles.label}>{children}</div>
переделал

2022-03-30 19:01 UTC, Bakivh commented on src/common/components/Input/Input.js
> +          {disabled && <img className={styles.buttonIcon} src={lockedIcon} />}
изменил

2022-03-30 19:02 UTC, Bakivh commented on src/common/components/Input/Input.js
> +            type="text"
вынес в props

2022-03-30 19:03 UTC, Bakivh commented on src/common/components/Input/Input.js
> +            defaultValue={value}
переименовал

2022-03-30 19:17 UTC, Bakivh commented on src/common/components/Input/Input.js
> +import xMediumIcon from "../../icons/x-medium.svg";
сделал

2022-03-30 19:18 UTC, Bakivh commented on src/common/components/Input/Input.js
> +import cx from "classnames";
done

2022-03-30 19:20 UTC, Bakivh commented
все исправил. кроме того что крестик должен показываться когда текст вбит, не очень понял как это сделать :(

2022-03-30 22:48 UTC, Muslik requested changes
Когда будешь дальше работать подумай над идеей отделения инпута от label :)

2022-03-30 22:48 UTC, Muslik commented on src/common/components/Input/Input.jsx
> +        {incorrect && (
Можешь сейчас сделать ```defaultValue && ()``` потом когда уже будешь делать рабочий инпут поменяешь

2022-03-30 22:48 UTC, Muslik commented on src/common/components/Input/Input.jsx
> +      <label className={styles.label} htmlFor={id}>
А теперь подумай как ты будешь такую штуку делать: https://ibb.co/8dbwS0z
Когда у тебя есть инпут без label. А у тебя компонент жестко привязан к label

2022-03-30 22:48 UTC, Muslik commented on src/common/components/Input/Input.jsx
> +  const [id] = useState(_uniqueId("prefix-"));
Ну во первых тут больше подходит useRef. А во вторых почему бы просто не обернут input в label и не нужен будет никакой id

2022-03-30 22:48 UTC, Muslik commented on src/common/components/Input/Input.jsx
> +  inputType = "text",
Просто type

2022-03-30 22:49 UTC, Muslik commented on src/common/components/Input/Input.js
> +          {incorrect && (
Ну сейчас onChange не нужно. Можешь статично задать что если есть defaultValue, то добавляешь кнопку.
Потом будете реализовывать рабочий функционал

2022-04-02 16:17 UTC, Bakivh commented on src/common/components/Input/Input.jsx
> +  inputType = "text",
done

2022-04-02 16:26 UTC, Bakivh commented on src/common/components/Input/Input.jsx
> +  const [id] = useState(_uniqueId("prefix-"));
я в начале так и делал. я думал ты наоборот сказал переделать :))) видимо не так понял. Можно  я пока так оставлю, через useRef пока не понял как делать

2022-04-02 16:29 UTC, Bakivh commented on src/common/components/Input/Input.jsx
> +        {incorrect && (
ок

2022-04-02 16:34 UTC, Bakivh commented on src/common/components/Input/Input.jsx
> +      <label className={styles.label} htmlFor={id}>
Сделал вывод лейбла только когда он не пустой

2022-04-03 15:35 UTC, Muslik requested changes
Нигде нет передачи пропса className. То есть я вашим компонентам банально не могу сделать отступы. Удалить лишние css файлы в папке uiKit, избавиться от стилей которые можно проверить просто по другим переданным аргументам. Стиль uiKit-а не соответствует макету. В консоли браузера есть ошибки. Также они в консоли когда вы запускаете проект.

2022-04-03 15:35 UTC, Muslik commented on package.json
> +    "classmates": "^1.0.1",
Удалить

2022-04-03 15:35 UTC, Muslik commented on src/common/components/Button/Button.jsx
> +  const buttonClass = cx(styles._, themeClass, sizeClass, {
```javascript
const buttonClassName = cx(styles._, {
  [styles[`theme_${theme}`]: true,
  [styles[`size_${size}`]: true,
})
```

2022-04-03 15:35 UTC, Muslik commented on src/common/components/Button/Button.jsx
> +    [styles.iconOnly]: style === "iconOnly",
Не нужно заставлять разработчика передавать еще одно свойство. Понять есть иконка или нет можно проверив пропс Icon. Понять если ли текст или нет проверив пропс children. props style тут лишний

2022-04-03 15:35 UTC, Muslik commented on src/common/components/Button/Button.jsx
> +  Icon = IconDefault,
Не нужна дефолтная иконка. Если ее нет, то значит будет только текст

2022-04-03 15:35 UTC, Muslik commented on src/common/components/Button/Button.jsx
> +  const buttonClass = cx(styles._, themeClass, sizeClass, {
И все проверки выше не нужны

2022-04-03 15:35 UTC, Muslik commented on jsconfig.json
> +{
https://ibb.co/10wGgMy вот сколько warning-ов я вижу когда запускаю ваш код. Плюс в консоли ошибки есть.

2022-04-03 15:35 UTC, Muslik commented on src/common/components/CheckBox/CheckBox.jsx
> +      <span>{label && <div className={styles.text}>{label}</div>}</span>
То есть если я label не передам, то отобразится просто пустой span ?

2022-04-03 15:35 UTC, Muslik commented on src/App.js
> +          <Dropdown styleList>
Весь этот код должен уехать в UiKit.jsx

2022-04-03 15:35 UTC, Muslik commented on src/ui-kit.css
>  body {
Все файлы внутри modules/ui-kit не нужны.
Там должны быть файлы-копмпоненты.

UiKit.jsx, UiKit.module.css

2022-04-03 15:35 UTC, Muslik commented on src/common/components/Input/Input.jsx
> +  const [id] = useState(_uniqueId("prefix-"));
Есть несколько вариантов.
1) Оставляй так, но следующее ДЗ я заблочу с таким вариантом :)
2) Разделить Input и Label И сделать отдельный компонент InputWithLabel. Либо юзать их по отдельности

2022-04-03 15:35 UTC, Muslik commented on src/common/components/Input/Input.jsx
> +  sizeShort,
Бесполезный пропс. Если нужно задавать явно какой то размер, то он будет приходить из пропса className (Которого кстати у вас нет)

2022-04-03 15:35 UTC, Muslik commented on src/common/components/Input/Input.jsx
> +      {label != "" && (
label && ()

Не нужно проверять именно на пустую строку

2022-04-03 15:35 UTC, Muslik commented on src/common/components/Input/Input.jsx
> +  const [id] = useState(_uniqueId("prefix-"));
Ваш вариант плох тем что вы забираете возможность передать тот id который я хочу. Он мне может понадобиться :)

2022-04-03 15:35 UTC, Muslik commented on src/common/components/Dropdown/Dropdown.jsx
> +  sizeShort = false,
А если потом появится padding: 32px, будет sizeShortX2 ? :)

Все это можно задать с помощью className. По умолчанию у вас будет padding: 16px, если вы из родителя передадите сюда отдельный className, будут другие свойства

2022-04-03 15:35 UTC, Muslik commented on src/common/components/Dropdown/Dropdown.jsx
> +  styleButtons = false,
Button не должен иметь представление о том что я буду в него вкладывать, поэтому если вам нужно делать отступы для кнопок, вы их будете делать передавая className в Button и там указывая margin

2022-04-03 15:35 UTC, Muslik commented on src/common/components/Button/Button.jsx
> +  width,
Переименовать в fullWidth. Он будет принимать true/false
По умолчанию false, если передать, то кнопка будет на всю ширину

2022-04-03 15:35 UTC, Muslik commented on src/common/components/RadioButton/RadioButton.module.css
> +._ > input:checked + span::before {
Мы назначаем классы и работаем с классами

2022-04-03 15:35 UTC, Muslik commented on src/common/components/RadioButton/RadioButton.jsx
> +      <span>{label && <div className={styles.text}>{label}</div>}</span>
Если label не указать то будет пустой тег

2022-04-03 15:35 UTC, Muslik commented on src/common/components/RadioButton/RadioButton.jsx
> +  name = shortid.generate(), // индивидуальный идентификатор для имени
Неа. Не должно быть такого что name автоматически генерируется. Если вы его не передали это нормально что Radio будет радотать некорректно

2022-04-03 17:43 UTC, Bakivh commented on package.json
> +    "classmates": "^1.0.1",
удалил

2022-04-03 18:02 UTC, Bakivh commented on src/common/components/Button/Button.jsx
> +  const buttonClass = cx(styles._, themeClass, sizeClass, {
понял

2022-04-03 18:21 UTC, Bakivh commented on src/common/components/Button/Button.jsx
> +    [styles.iconOnly]: style === "iconOnly",
да, переделал

2022-04-03 18:21 UTC, Bakivh commented on src/common/components/Button/Button.jsx
> +  Icon = IconDefault,
ок

2022-04-03 18:22 UTC, Bakivh commented on src/common/components/CheckBox/CheckBox.jsx
> +      <span>{label && <div className={styles.text}>{label}</div>}</span>
Да, это нужно для кастомного чекбокса. По крайней мере я такую его реализацию нашел в сети (со спаном)

2022-04-03 18:30 UTC, Bakivh commented on src/App.js
> +          <Dropdown styleList>
перенес

2022-04-03 18:33 UTC, Bakivh commented on src/ui-kit.css
>  body {
убрал

2022-04-03 18:35 UTC, Bakivh commented on src/common/components/Input/Input.jsx
> +      {label != "" && (
ок

2022-04-03 18:44 UTC, Bakivh commented on src/common/components/Button/Button.jsx
> +  width,
сделал

2022-04-03 18:45 UTC, Bakivh commented on src/common/components/RadioButton/RadioButton.module.css
> +._ > input:checked + span::before {
Джабраил, я не понял что ты имел в виду :)
как правильно надо сделать?

2022-04-03 18:46 UTC, Bakivh commented on src/common/components/RadioButton/RadioButton.jsx
> +      <span>{label && <div className={styles.text}>{label}</div>}</span>
ну да. Также как и с чекбоксом - так работает этот кастомный чекбокс

2022-04-03 19:39 UTC, Bakivh commented on src/common/components/RadioButton/RadioButton.jsx
> +  name = shortid.generate(), // индивидуальный идентификатор для имени
исправил

2022-04-03 19:49 UTC, Muslik commented on src/common/components/RadioButton/RadioButton.module.css
> +._ > input:checked + span::before {
input:checked должно стать .input:checked

2022-04-03 19:57 UTC, Muslik commented on src/common/components/Dropdown/Dropdown.module.css
> +
Все комменты удалить

2022-04-03 19:57 UTC, Muslik commented on src/common/components/CheckBox/CheckBox.jsx
> +      <span>{label && <div className={styles.text}>{label}</div>}</span>
Ок.

2022-04-03 20:14 UTC, Bakivh commented on src/common/components/Dropdown/Dropdown.module.css
> +
удалил

2022-04-03 20:44 UTC, Bakivh commented on jsconfig.json
> +{
исправил все

2022-04-03 20:49 UTC, Bakivh commented on src/common/components/RadioButton/RadioButton.module.css
> +._ > input:checked + span::before {
сделал

2022-04-03 21:02 UTC, Bakivh commented on src/common/components/Input/Input.jsx
> +  sizeShort,
Я не понимаю как это будет в итоге :((
у меня ведь на это свойстве завязано две состовляющих инпута 
.sizeShort .input {
  width: 128px;
}
.sizeShort .inputText {
  width: 112px;
}

т.е. я буду писать потом <Input className = "sizeShort"> ?
Я думал что компонент это как объект и внутри его кухня вся должна быть "скрыта"

2022-04-03 21:37 UTC, Bakivh commented on src/common/components/Dropdown/Dropdown.jsx
> +  styleButtons = false,
исправил

2022-04-03 21:48 UTC, Bakivh commented on src/common/components/Dropdown/Dropdown.jsx
> +  sizeShort = false,
сделал

2022-04-04 14:22 UTC, Muslik commented on src/common/components/Input/Input.jsx
> +  sizeShort,
Неа. Вы будете писать не так.
Ну представьте что я беру ваш стилизованный инпут и он будет у меня в 20 местах. И везде разных размеров. Неправильно будет если для каждого такого варианта буду делать отдельный пропс.
Ты будешь указывать длину там где ты используешь Input:

Допустим в UiKit.jsx
<Input className={styles.firstInput} />
<Input className={styles.secondInput} />

Далее в UiKit.module.css
.firstInput { width: 200px; }
.secondInput { width: 250px; }

2022-04-04 14:28 UTC, Muslik commented on src/common/components/Dropdown/Dropdown.jsx
> +  sizeShort = false,
Ну да. Все логично ) import styles в UiKit перенесите ниже

2022-04-04 14:30 UTC, Muslik requested changes
Работа все еще не соответствует дизайну в макете.

2022-04-04 20:26 UTC, Bakivh commented on src/common/components/Dropdown/Dropdown.jsx
> +  sizeShort = false,
спасибо, перенес )

2022-04-04 20:28 UTC, Bakivh commented on src/common/components/Input/Input.jsx
> +  sizeShort,
Дело в том, что ширина задается не у компонента Input а в его внутреннем элементе.
Как это тогда реализовать ?

2022-04-04 21:31 UTC, Bakivh commented on src/common/components/Input/Input.jsx
> +  sizeShort,
В общем сделал тогда перенос classNamе к элементу компонента. Не знаю правильно ли или нет

2022-04-04 21:32 UTC, Bakivh commented
Сейчас макет полностью соответствует дизайну который был

2022-04-05 01:34 UTC, Muslik commented on src/common/components/Button/Button.jsx
> +  switch (size) {
switch быть не должно. Уже писал про это

2022-04-05 01:36 UTC, Muslik commented on src/modules/ui-kit/UiKit.jsx
> +            <CheckBox className={styles.listInDropdown} label="Подтвержден" />
В figma в макете этот вариант выбранный. В твоем случае я не могу поставить элемент выбранным по умолчанию. Потому что он не принимает соответствующих пропсов

2022-04-05 01:37 UTC, Muslik commented on src/modules/ui-kit/UiKit.jsx
> +  const uniq_name1 = shortid.generate(); // для радиобуттона
Не нужна эта генерация рандомного id. Вы же его для name используете. Просто в name передаете статичное значение

2022-04-05 01:37 UTC, Muslik commented on src/common/components/Dropdown/Dropdown.jsx
> +  //sizeShort = false,
Удалить

2022-04-05 01:38 UTC, Muslik commented on src/modules/ui-kit/UiKit.jsx
> +          <Dropdown sizeShort label="Выберите тему">
sizeShort нет такого пропса

2022-04-05 01:38 UTC, Muslik commented on src/common/components/Button/Button.jsx
> +  Icon,
nit:

icon: Icon

И везде пропс icon можно будет называть с маленькой буквы

2022-04-05 01:39 UTC, Muslik commented on src/common/components/RadioButton/RadioButton.jsx
> +  // name = shortid.generate(), // индивидуальный идентификатор для имени
убрать

2022-04-05 01:40 UTC, Muslik commented on src/common/components/Input/Input.jsx
> +            <XMediumIcon className={styles.icon} />
Крестик не по центру

2022-04-05 01:40 UTC, Muslik requested changes
Замечания написал

2022-04-05 05:21 UTC, Bakivh commented on src/common/components/Input/Input.jsx
> +            <XMediumIcon className={styles.icon} />
исравил

2022-04-05 05:21 UTC, Bakivh commented on src/common/components/RadioButton/RadioButton.jsx
> +  // name = shortid.generate(), // индивидуальный идентификатор для имени
ок

2022-04-05 05:22 UTC, Bakivh commented on src/common/components/Button/Button.jsx
> +  Icon,
done

2022-04-05 05:35 UTC, Bakivh commented on src/modules/ui-kit/UiKit.jsx
> +          <Dropdown sizeShort label="Выберите тему">
убрал

2022-04-05 05:35 UTC, Bakivh commented on src/common/components/Dropdown/Dropdown.jsx
> +  //sizeShort = false,
done

2022-04-05 05:37 UTC, Bakivh commented on src/modules/ui-kit/UiKit.jsx
> +  const uniq_name1 = shortid.generate(); // для радиобуттона
done

2022-04-05 05:39 UTC, Bakivh commented on src/modules/ui-kit/UiKit.jsx
> +            <CheckBox className={styles.listInDropdown} label="Подтвержден" />
сделал

2022-04-05 05:43 UTC, Bakivh commented on src/common/components/Button/Button.jsx
> +  switch (size) {
исправил, я думал это nit был =)

2022-04-07 21:36 UTC, Muslik requested changes
В целом все неплохо. У вас в консоли ошибка еще. Исправьте ее.

2022-04-07 21:36 UTC, Muslik commented on src/common/components/Button/Button.jsx
> +  function capitalize(s) {
Функцию вынести за пределы компоненты

2022-04-07 21:36 UTC, Muslik commented on src/common/components/Button/Button.jsx
> +  let sizeClass;
Неиспользуемые переменные

2022-04-07 21:36 UTC, Muslik commented on src/common/components/Dropdown/Dropdown.jsx
> +        {label && <label className={styles.label}>{label}</label>}
А для чего тут label? Инпута же не будет. Просто span или div

2022-04-07 21:36 UTC, Muslik commented on src/common/components/Dropdown/Dropdown.jsx
> +    <>
Зачем div оборачивать еще и в fragment

2022-04-07 21:36 UTC, Muslik commented on src/common/components/Input/Input.jsx
> +  sizeShort,
Все ненужные пропсы и класы удалить. Включая закоментированные куски кода

2022-04-07 21:36 UTC, Muslik commented on src/common/components/Input/Input.jsx
> +  sizeShort,
Все легко получается. Вы внутреннему элементу (тексту) задаете width 100%. Он всегда будет тянуться на максимум. В дальнейшем вы через className можете поменять длину инпута. А текст автоматически подставится под него. Иначе сейчас некрасиво получается: https://ibb.co/V9KyZLC

2022-04-07 21:36 UTC, Muslik commented on src/common/components/Button/Button.jsx
> +  function capitalize(s) {
Вы же в теории можете переиспользовать ее во всем проекте. Положите ее в папку:
common/helpers/capitalize.js

2022-04-07 21:37 UTC, Muslik commented on src/modules/ui-kit/UiKit.jsx
> +import shortid from "shortid";
Вы нигде не используете

2022-04-07 21:57 UTC, Bakivh commented on src/common/components/Button/Button.jsx
> +  function capitalize(s) {
done

2022-04-07 21:58 UTC, Bakivh commented on src/common/components/Button/Button.jsx
> +  let sizeClass;
done

2022-04-07 22:05 UTC, Bakivh commented on src/common/components/Dropdown/Dropdown.jsx
> +        {label && <label className={styles.label}>{label}</label>}
ok

2022-04-07 22:06 UTC, Bakivh commented on src/common/components/Dropdown/Dropdown.jsx
> +    <>
убрал

2022-04-07 22:11 UTC, Bakivh commented on src/modules/ui-kit/UiKit.jsx
> +import shortid from "shortid";
ну да, убрал

2022-04-09 17:04 UTC, Bakivh commented
все исправил

2022-04-10 21:53 UTC, Muslik approved these changes

2022-04-11 06:19 UTC, merged